//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSideApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineBankingEntities : DbContext
    {
        public OnlineBankingEntities()
            : base("name=OnlineBankingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountDetailsTable> AccountDetailsTables { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TransactionHistoryTable> TransactionHistoryTables { get; set; }
        public virtual DbSet<TransactionsTable> TransactionsTables { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserInRole> UserInRoles { get; set; }
        public virtual DbSet<QueryTable> QueryTables { get; set; }
    }
}
