//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSideApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsTable
    {
        public decimal TransactionId { get; set; }
        public decimal AccNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> FromAccNumber { get; set; }
        public Nullable<decimal> ToAccNumber { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
    }
}
